RubyOnRails/vendelo/config/routes.rb
Rails.application.routes.draw do
  get '/products', to: 'products#index'
  get '/products/new', to: 'products#new', as: :new_product
  get '/products/:id', to: 'products#show', as: :product
end

RubyOnRails/vendelo/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

RubyOnRails/vendelo/app/models/product.rb
class Product < ApplicationRecord
end

RubyOnRails/vendelo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

RubyOnRails/vendelo/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    
  end
end

RubyOnRails/vendelo/app/helpers/application_helper.rb
module ApplicationHelper
end

RubyOnRails/vendelo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vendelo | Compra y vende productos de 2da mano</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/header'%>
    <%= yield %>
  </body>
</html>

RubyOnRails/vendelo/app/views/products/index.html.erb
<h1>Productos</h1>

<% @products.each do |product| %>
  <%= link_to product_path(product.id), class: 'product' do%>
    <h2> <%= product.title%> </h2>
    <span> <%= product.price%>$ </span>
  <%end%>
<% end %>

RubyOnRails/vendelo/app/views/products/new.html.erb
<h2> Añadir producto </h2>

<%= form_with model: @product do |form|%>

<%end%>

RubyOnRails/vendelo/app/views/products/show.html.erb
<h1 class='title'> <%=@product.title %> </h1>
<p class='description'> <%=@product.description%> </p>

<span class='price'> <%=@product.price%> </span>

RubyOnRails/vendelo/app/views/shared/_header.html.erb
<h1> Vendelo </h1>